export const sellers = [
    {
      id: 1,
      image: "/images/seller1.svg",
      name: "Michael Johnson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 20000.00,
    },
    {
      id: 2,
      image: "/images/seller2.svg",
      name: "Emily Brown",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 18000.00,
    },
    {
      id: 3,
      image: "/images/seller3.svg",
      name: "David Wilson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 25000.00,
    },
    {
      id: 4,
      image: "/images/seller4.svg",
      name: "Sarah Johnson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 22000.00,
    },
    {
      id: 5,
      image: "/images/seller1.svg",
      name: "David Wilson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 28000.00,
    },
    {
      id: 6,
      image: "/images/seller2.svg",
      name: "Emily Brown",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 19000.00,
    },
    {
      id: 7,
      image: "/images/seller3.svg",
      name: "Michael Johnson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 23000.00,
    },
    {
      id: 8,
      image: "/images/seller4.svg",
      name: "Michael Johnson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 21000.00,
    },
    {
      id: 9,
      image: "/images/seller1.svg",
      name: "Michael Johnson",
      registered: "Aug 06, 2023",
      country: "USA",
      group: "Default",
      earn: 24000.00,
    },
  ];
